export const members = [
	{
		"accountName": "ay",
		"lastName": "Yadagani",
		"firstName": "Amulya",
		"department": "TimeIncIndia",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "amulya.yadagani@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": true,
		"lastLogin":new Date("8/16/2017")

	}, {
		"accountName": "jh",
		"lastName": "Hirpara",
		"firstName": "Jasmine",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "jh@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": true,
		"lastLogin":"NO login"

	}, {
		"accountName": "at",
		"lastName": "Tripathi",
		"firstName": "Anant",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "at@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": true,
		"lastLogin":new Date("2017-08-16")

	}, {
		"accountName": "db",
		"lastName": "Behera",
		"firstName": "Debasis",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "db@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-20")
	}, {
		"accountName": "jp",
		"lastName": "Putel",
		"firstName": "Jaleswar",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "jp@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-16")
	}, {
		"accountName": "pd",
		"lastName": "Dhingra",
		"firstName": "Pankhuri",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "pd@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-16")
	}, {
		"accountName": "pk",
		"lastName": "Krishnasamy",
		"firstName": "Priya",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "pk@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-16")
	}, {
		"accountName": "ss",
		"lastName": "Senapati",
		"firstName": "Sabyasachi",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "ss@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-16")
	},
	{
		"accountName": "sv",
		"lastName": "Vinayaka",
		"firstName": "Siddhi",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "sv@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-16")

	}, {
		"accountName": "sc",
		"lastName": "Choudhary",
		"firstName": "Sunesh",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "sc@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-16")
	}, {
		"accountName": "sp",
		"lastName": "Panda",
		"firstName": "Swagatika",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "sp@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": true,
		"lastLogin":new Date("2017-08-16")
	}, {
		"accountName": "tv",
		"lastName": "V",
		"firstName": "ThulasiPriya",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "tv@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-16")
	}, {
		"accountName": "va",
		"lastName": "Arora",
		"firstName": "Vikas",
		"department": "TimeInc.India",
		"company": "DTN",
		"phnNumber": "+1-212-467-1280",
		"email": "va@timeinc.com",
		"type": "Person",
		"status": "Current",
		"isActive": false,
		"lastLogin":new Date("2017-08-15")

	}];